version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins'
      - '/etc/timezone:/etc/timezone'
      - '/etc/localtime:/etc/localtime'      
volumes:
  jenkins_data:
    driver: local
